version: '3'
services:
  db:
    image: postgres
    volumes:
      - .db:/var/lib/postgresql/data
  web:
    build: ./docker
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - ./bundle-cache:/usr/local/bundle
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - db